### PR TITLE
Sample GUI

### PR DESCRIPTION
**Pull request by GoreevArtem**

### CODE REVIEW

**Comment by GoreevArtem** [comment]
added a gui example
@DumDereDum review pls

**Review by DumDereDum — COMMENTED** [review]
Wait for merging this PR https://github.com/DumDereDum/Magic-Piano/pull/27
After that update your branch to main, and I'll merge this PR

**Comment by GoreevArtem** [comment]
ok

**Comment by DumDereDum** [comment]
@GoreevArtem, update PR

**Pull request closed without merging**
